# makfile configuration
all: pong.elf

CPU             	= msp430g2553
CFLAGS          	= -mmcu=${CPU} -Os -I../h -I../h
LDFLAGS	                = -L../lib -L/opt/ti/msp430_gcc/include/

#switch the compiler (for the internal make rules)
CC              = msp430-elf-gcc
AS              = msp430-elf-as -mmcu=${CPU} -c

#additional rules for files
pong.elf: ${COMMON_OBJECTS} pong.o wdt_handler.o buzzer.o
	${CC} ${CFLAGS} ${LDFLAGS} -o $@ $^ -lTimer -lLcd -lShape -lCircle -lp2sw


load: pong.elf
	mspdebug rf2500 "prog $^"

clean:
	rm -f *.o *.elf